Fix/issue64/php7 (#79)
* Fixed #64 - deprecated mongodb-odm syntax in PHP 7

Symptom:

Fatal error: Cannot use 'String' as class name as it is reserved
in /Users/asrob/Sites/warden/vendor/doctrine/mongodb-odm/
lib/Doctrine/ODM/MongoDB/Mapping/Annotations/String.php on line 23
when running "composer install"

This is because 'String' is a reserved word in PHP 7:
http://php.net/manual/en/reserved.other-reserved-words.php

Although there was a fix here which checked the PHP version...

https://github.com/doctrine/mongodb-odm/issues/1168

... the String class is still dynamically loaded when referred
to in a Docblock annotation, like this: @String (or @Bool etc.)

Doctrine have deprecated over a dozen annotations like @String
in favour of @Field, where you must specify the type like this:

    /**
     * @Field(type="string")
     */

     protected $foo;

NB: 'string' is the default type anyway.

In Warden, it's @Mongodb\Field... because of the 'use' statement

Official docs for @Field (and other annotations):
http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/annotations-reference.html#field

Allowed field types:
http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#doctrine-mapping-types

* Update mongodb-odm to 1.1 for PHP7 (5.6 new minimum)

This isn't necessary to fix issue #64, but it provides compatibility
with MongoDB drivers - see https://github.com/doctrine/mongodb-odm/releases

Note this new version requires PHP 5.6+

Documentation suggests 1.0.x branch will lose support after Dec 2016.